### ISSUE TITLE
Moonlinght's El Rail and BTM don't cross RHW properly

### ISSUE THREAD

**Issue by zsc4** [NAMTeam/Network-Addon-Mod#111]
When crossing an RHW, both Moonlinght's BTM and his El Rail revert to the underlying networks, although they resume their proper form after the crossing.

**Comment by MGB204** [comment]
I'm happy to take this on. 

I've already got the El-Rail models sorted. Sadly the nature of ML's models means there are some limitations to these crossings. In addition parts of the models overhang the RHW on certain setups (RHW-6S/Diagonals). This is caused by models which are not part of the crossings, so can not easily be resolved.

As for T21s, should they have the IDs changed to match P57 IDs or keep the old ones? I'm pretty certain it's the former, but I just wanted to check.

**Comment by MGB204** [comment]
Issue resolved as of NAM35.

I still need to add the T21s for BTM though. Plus currently the only included crossings are limited to those originally supported. I do hope to improve on this to make them more compatible.
