### ISSUE TITLE
RRW lot textures

### ISSUE THREAD

**Issue by swordmasterSC4** [NAMTeam/Network-Addon-Mod#202]
![](http://www.ld-host.de/uploads/images/881fd23422dbaf6c0c07ac899e5d6c8a.jpg)

**Comment by MGB204** [comment]
Is this strictly necessary?

The Lot Textures have been assigned wealthing due to the IDs used. A fix would only involve new IDs for these textures. That could be problematic, since lots have likely been created using them.

To ensure the desired texture appears you can simply set the property "Wealth" in the buildings exemplar of a lot as follows:

  0x00 (no wealth)    - Ortho STR
  0x01 (low wealth)   - Ortho STR End
  0x02 (med wealth) - Diag STR
  0x03 (high wealth) - Diag STR End

**Comment by jflann** [comment]
![image](https://user-images.githubusercontent.com/26899145/122846576-bf067e80-d2cb-11eb-9851-6e1cd4ccc9ce.png)

textures look to have been re-ID'd since this issue was raised, I am assuming it is resolved.
