### ISSUE TITLE
Bad rotations on OWR-1 Tees

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#303]
![image](https://user-images.githubusercontent.com/26899145/128263117-05d0bbbf-937d-4b22-9811-5cfed52d5163.png)
![image](https://user-images.githubusercontent.com/26899145/128263142-bc8ba7a0-8103-4dd7-b6e0-a5f8928d53b7.png)

**Comment by jflann** [comment]
![image](https://user-images.githubusercontent.com/26899145/128264525-b6a511b5-dea6-4b82-afbe-e1cd9c21c2a2.png)
![image](https://user-images.githubusercontent.com/26899145/128264575-93a415da-1b9d-4463-ade7-607df0be8041.png)

**Comment by TarkusSC4** [comment]
Issue is texture-rotation-related.  The RULs for them match those for related T-ints, but the OWR-1 ones were originally rotated inconsistent with the others, and weren't caught during the re-rotation process in P51.  I've since fixed them in the OWR-1 .dat file on my end, and also redesigned the OWR-2-ending-in-OWR-1 T in such a way to discourage its usage (the lane math doesn't work, and it only exists in order to allow the OWR-1 x OWR-1 T-ints).
