### ISSUE TITLE
FLEX-WT 8C to 10S broken

### ISSUE THREAD

**Issue by jflann** [NAMTeam/Network-Addon-Mod#355]
As memo astutely observed, the LHD/RHD versions of this transition are in conflict.  When we split the code into RHD/LHD parts, the load order changed and the LHD code was loaded first.  This caused the RHD configuration to break.  Reverting to the original load order, the LHD version breaks.

Image from NAM 45 controller and INRULs (LHD).

![image](https://user-images.githubusercontent.com/26899145/215628010-68b001a7-1f0a-4b7e-9e2d-8d93f741de1b.png)

**Comment by TarkusSC4** [comment]
As determined earlier in the Discord discussion, the issue seems to be due to the fact that the arrows are on different tiles (800/900/A00/B00) on S-to-C transitions in which the S network is wider (as is the case here), than when the C network is wider (400/580/600/780, as is the case with the default 6C-to-4 setup).  As a result, the INRUL differentiation isn't there, which results in the RHD and LHD code having the same left side to the override.

I'll be looking into a solution for this, hoping to have it in place by NAM 47 Build 02.  The issue does appear (fortunately) to be strictly cosmetic, so the functionality of the transitions is still in tact.
